a3: ./src/a3w23.c++ ./src/server.c++ ./src/client.c++
	g++ -c ./src/a3w23.c++
	g++ -c ./src/server.c++
	g++ -c ./src/client.c++
	g++ -o a3w23 a3w23.o server.o client.o

clean:
	rm a3w23.o
	rm server.o
	rm client.o
	rm a3w23
